name: Check Code Quality with Sonarcloud

on:
  pull_request:
  push:
    branches:
      - master
      - staging
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    name: Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15 # should not run more than 15 minutes max

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: install node dependecies
        run: yarn

      - name: test with coverage
        run: yarn test:coverage

      - name: Scan with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.CI_SONAR_TOKEN }}
