name: Lint

on:
  push:
    branches:
      - '**'
      - '!staging'
      - '!master'
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: Run ESLint and check offenses
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependecies
        run: yarn

      - name: Run ESLint
        run: yarn lint
